# Generated by Django 5.1.2 on 2025-11-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_projectimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, help_text="Bootstrap Icon p.sh. 'bi-camera-video' ose 'bi-fingerprint'", max_length=50),
        ),
    ]
